server:
  port: 8888

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
#公共配置与profiles选择无关
mybatis-plus:
#  typeAliasesPackage: com.example.demo
#  mapperLocations: classpath*:mapper/*Mappper.xml
  configuration:
    #sql语句打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    call-setters-on-nulls: true
    auto-mapping-behavior: full
  global-config:
    db-config:
      id-type: id_worker

# 数据源配置demo
#spring:
#  datasource:
#    url: jdbc:mysql://192.168.17.47:3306/hb_databank?autoReconnect=true&useUnicode=true&zeroDateTimeBehavior=convertToNull&useServerPrepStmts=false&rewriteBatchedStatements=true&serverTimezone=GMT%2B8
#    username: root
#    password: 123
#    driverClassName: com.mysql.cj.jdbc.Driver
#    # 使用druid数据源
#    type: com.alibaba.druid.pool.DruidDataSource
#    # 配置获取连接等待超时的时间
#    # 下面为连接池的补充设置，应用到上面所有数据源中
#    # 初始化大小，最小，最大
#    # 配置获取连接等待超时的时间
#
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 60000
#      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
#      time-between-eviction-runs-millis: 60000
#      # 配置一个连接在池中最小生存的时间，单位是毫秒
#      min-evictable-idle-time-millis: 30000
#      validation-query: SELECT 1 FROM DUAL
#      pool-prepared-statements: true
#      max-pool-prepared-statement-per-connection-size: 20
#      # 通过connectProperties属性来打开mergeSql功能，慢SQL记录 3000ms的为慢sql
#      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=3000

